### ISSUE TITLE
Add installation instruction to the readme

### ISSUE THREAD

**Issue by chrisgorgo** [mslw/osirix-bids-output#1]
It's hard for a new user to figure out how to install this plugin. It also depends on external packages (dcm2niix) which are not listed.

**Comment by chrisgorgo** [comment]
I might be also good to provide precompiled binaries attached to GitHub releases. This could be automated for Windows, Mac, and Linux via Travis and AppVeyor. Checkout the dcm2niix repo for example config files.

**Comment by mslw** [comment]
You are correct. However, it will take a couple of adjustments before the plugin is ready for installation (e.g. dcm2niix and output paths are hardcoded ATM), but when I'm done I will certainly add a binary and installation instructions (and close this issue). The binary will be MacOS only though, since Horos itself is made for OS X. I admit that listing dcm2niix is an omission on my part and I'll fix it promptly.

**Comment by mslw** [comment]
Done and done. I'm pleased to say that v0.1 is out!
