### ISSUE TITLE
Fieldmaps from AP-PA EPIs

### ISSUE THREAD

**Issue by bkossows** [mslw/osirix-bids-output#9]
Hi,
we are still big fans of Your toolbox! I wonder if You can add a support for AP-PA pairs of EPIs for a field mapping? It is now a standard instead of a double-echo GRE.
Please take a look at the following specification - https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar. Fieldmaps would need to be placed in a separate folder with a respective suffix (-dir). I suppose it can be done by adding a new option to a drop-out list (eg. fmap-ap and fmap-pa).
Warm regards!
B.

**Comment by mslw** [comment]
Hi, I'm happy to hear that!

For me, the biggest problem with Horos and this plugin is that it is specific to MacOS. I'm no longer in the apple ecosystem, so I don't have the motivation or ability to work on this project any more. But if you (or people at the lab) have the power to work on it together (building and running any code basically has to happen in Xcode) then I think we could coordinate through GitHub to make it happen.

You're right that the "pepolar" fieldmap should be added an option in the dropout list, and logic for handling the option should be implemented. Currently there's quite a bit of a dance to get the double echos right (they're stored in Horos as three series with the same name, so we check dicom fields to see which is which; additionally we tweak filenames a little post-export because dcm2niix makes its own tweaks). These field maps would probably need some custom logic too, but it shouldn't be too hard.

The most important question is: how are these AP-PA pairs seen by Horos: one DicomSeries (shown as a row in GUI) or multiple, same or different names? How does dcm2niix handle them by default?

Once we know what exactly needs to be done, we can open a PR and go back and forth there. From my side, I could provide pointers to what happens in the code, and probably make the actual code changes (but I'd be going blind with the ability to run it). You'd need to check if the code runs, do actual debugging, and make at least some of the changes (e.g. the pull down values are in the xib files, which are saved as text but basically illegible without Xcode - though it would be cool if you also want to take a stab at the logic). The coding work shouldn't be too large, it's the ability to run the code it that's the hard part.

**Comment by bkossows** [comment]
It does not sound as a "no". Thank You for the reply :)

Yes, there are actually 2 series (names/rows) as it would be in case of 2 additional EPI series. The only thing, which seems to be done is to add another "modality" (or two) in https://github.com/mslw/horos-bids-output/blob/75f8b778d4b5c3c1149083563d4a9460b8d3e434/OBOSeries.m. In the end both series should be placed in the same "fmap" directory but with a different suffix dir-AP and dir-PA respectively.

**Comment by mslw** [comment]
This is good news - if we can assume that users will be able to annotate whether it's AP or PA based on the seies file name, then it should be easy! Looks like the `OBOExporter` shouldn't need tweaks if `OBOSeries` will be able to report a correct file name.

The only problem on the code/UI side I can see is that the actual suffix is `_epi`, and the filename goes `... _dir-<label>[_run-<index>]_epi`. So in the mapping window we either need to a new column (for `dir`) or add two "fake" suffixes, eg. "(epi-pa)" and ("epi-ap") - similar to how we have "(fmap)" to represent phasediff and magnitude stored in the same file. I like the second approach better. With that, we would also need to make `GeneralMappingWindowController` translate the GUI value into a proper suffix and additional parameters (just as it's done for "(fmap)").

So the TODO seems to be as follows:
- [ ] add new options to the pull-down list (in xib file, so best done from Xcode GUI)
- [ ] interpret the new options in `GeneralMappingWindowController`
- [ ] add `_epi` suffix to the list of field map suffixes in `OBOSeries::getBidsPath`, just as you pointed out
- [ ] in the same function, when building a field map path, also add `dir-<label>` part, but only if the suffix is `_epi`
- [ ] bump the two version strings in `version.plist` from 1.0 to 1.1

Points 3-5 seem straightforward, and either of us can do it. I can do 2, and you have to do 1 (we can coordinate on the details) and later check if all works.

We have two ways to go about sharing the code. Either you can start a pull request (with any of the little things) or I can get things going with a new  branch (tomorrow afternoon at the earliest).
